"""empty message

Revision ID: 8c1b2b349a76
Revises: 
Create Date: 2021-07-21 15:01:55.515749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1b2b349a76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rdatatime', sa.String(length=15), nullable=True),
    sa.Column('hongpan', sa.Integer(), nullable=True),
    sa.Column('lvpan', sa.Integer(), nullable=True),
    sa.Column('realzhangting', sa.Integer(), nullable=True),
    sa.Column('dieting', sa.Integer(), nullable=True),
    sa.Column('zhaban', sa.Integer(), nullable=True),
    sa.Column('lianban', sa.Integer(), nullable=True),
    sa.Column('lianban2', sa.Integer(), nullable=True),
    sa.Column('liangban3', sa.Integer(), nullable=True),
    sa.Column('liangban3gegu', sa.String(length=1000), nullable=True),
    sa.Column('liangban3up', sa.Integer(), nullable=True),
    sa.Column('liangban3upgegu', sa.String(length=256), nullable=True),
    sa.Column('Total', sa.Integer(), nullable=True),
    sa.Column('zhangdie', sa.Enum('涨', '跌', '平', '休'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood_table')
    # ### end Alembic commands ###
